import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/src/components/NavBar";
import AntdRegistry from "@/src/hooks/antd";
import AuthProvider from "@/src/components/Auth/Provider";
import { ReactNode, Suspense } from "react";
import Script from "next/script";
// import { Main, NextScript } from "next/document";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "E-Commerce App",
  description: "Generated by GrooveTech",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: ReactNode;
  modal: ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src={`https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY`}
          async
          // defer
        />
        <Script
          async
           src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"
           crossOrigin="anonymous"
          // defer
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>

          <NavBar />
          <AntdRegistry>{children}</AntdRegistry>
          {modal}
        </AuthProvider>
        {/* <Main />
        <NextScript /> */}
      </body>
    </html>
  );
}
